pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yii2app"
        DOCKERHUB_USERNAME = "pandu321"
        EC2_USER = "ubuntu"
        EC2_IP = "13.60.76.230"
        SSH_KEY = credentials('jenkins-ssh-key') // private key (PEM format)
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE}:latest ./app"
            }
        }

        stage('Login & Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh """
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                            docker push ${DOCKER_USER}/${DOCKER_IMAGE}:latest
                        """
                    }
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh """
                    ssh -o StrictHostKeyChecking=no -i ${SSH_KEY} ${EC2_USER}@${EC2_IP} \\
                    'docker service update --image ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE}:latest yii2_service'
                """
            }
        }
    }
}
